### ISSUE TITLE
`<br>` tags being left on the share for stats page `/at/[handle]`

### ISSUE THREAD

**Issue by shivan-s** [jycouet/jyc.dev#2] opened 2024-11-05 08:34 UTC
BTW, this is so cool!

I am using firefox on mac.

We expect no `<br>` tags in the final post.

<img width="512" alt="Screenshot 2024-11-05 at 9 26 12 PM" src="https://github.com/user-attachments/assets/0b17dbc3-b4aa-4f63-b798-739983754024">

However! I wonder if this is a bug with the bsky app and the implementation here is perfect. Hence this issue is just for your information.

https://github.com/user-attachments/assets/43016075-d1ba-497b-a8e3-65b0ff7afaa2

**Comment by shivan-s** [comment] 2024-11-05 08:35
Code: https://github.com/jycouet/jyc.dev/blob/6ec3e8b354e96f9e45aa3b36d3739e82465812b1/src/routes/at/%5Bhandle%5D/%2Bpage.svelte#L165

Potentially, removing the `<br>` tags and preserving the `\n`.

**Comment by shivan-s** [comment] 2024-11-05 08:39
I'm wondering if:
- #1 
did fix the issue by @jeffque?

Let me know what y'all think.

**Comment by jeffque** [comment] 2024-11-05 09:39
> I'm wondering if:
> 
> - #1 
> 
> did fix the issue by @jeffque?
> 
> 
> 
> Let me know what y'all think.
> 
> 

Unfortunately no, it did not solve.

**Comment by jycouet** [comment] 2024-11-05 10:20
I think that it's a bsky issue.

On Windows & Chrome only `<br>` works and `\n` are ignored
On Mac & Firefox `\n` is working, but `<br>` is showing

---

https://github.com/bluesky-social/social-app/issues/3042
https://github.com/bluesky-social/social-app/issues/5738

**Comment by shivan-s** [comment] 2024-11-05 18:32
Ahh, I thought so. I'll leave it up to you to open or closw this issue. Sorry to have bothered you.

**Comment by jycouet** [comment] 2024-11-06 00:52
Not bothered at all. I'll keep it open, and will see how I can help in one of the bsky ticket when I find a bit of time 👍

**Comment by jycouet** [comment] 2024-11-06 21:41
I'm not able to reproduce in Windows. I tried witht he source also of the app, but no. So I filled an issue.
Let's see if someone can give us a hint.

**Comment by jycouet** [comment] 2024-11-07 15:12
I just had a billiant _(maybe)_ idea! Could you test it on Mac now ?

**Comment by jeffque** [comment] 2024-11-07 16:54
@jycouet , I'll test it!

Firefox, Safari and Chrome are the browsers I have at my disposal

**Comment by jeffque** [comment] 2024-11-07 16:58
@jycouet 

Firefox + Mac

https://bsky.app/profile/jeffquesado.ulivre.dev/post/3laeq2lsddj2j

It posted correctly, but the preview was not the greatest one. I am happy with the result btw!

**Comment by jeffque** [comment] 2024-11-07 17:02
Safari

https://bsky.app/profile/jeffquesado.ulivre.dev/post/3laeqbs75yr2j

**Comment by jycouet** [comment] 2024-11-07 17:03
I'm not sure I get it

![image](https://github.com/user-attachments/assets/60196844-b79d-45a3-bb1e-ccf7045f5cdd)

**Comment by jycouet** [comment] 2024-11-07 17:04
The post on top is the result of the preview? or?

**Comment by jeffque** [comment] 2024-11-07 17:05
Finally, Chrome https://bsky.app/profile/jeffquesado.ulivre.dev/post/3laeqjtqhoj2h

**Comment by jeffque** [comment] 2024-11-07 17:09
> The post on top is the result of the preview? or?

![image](https://github.com/user-attachments/assets/af92f77f-6aaf-4d7a-9ac5-d93a111119fd)

I tried to annotate in the image itself. Above is the post itself. Bellow (the post with a print image) is how I saw it in the "new post" component

**Comment by jycouet** [comment] 2024-11-07 17:21
`<br> vs \n` not a browser issue, it's a Mac / Windows issue. And looking at the end result, like you said, I think also that it's ok.

For the preview, you have to "validate" the preview. (I think that it's not possible from my end :/)

Would you agree to close it ? :) (I let you do it if yes, if not, I let you answer :D)

**Closed as completed** 2024-11-07 19:40 UTC

**Comment by shivan-s** [comment] 2024-11-07 21:41
Thanks for looking into this :)
